### ISSUE TITLE
malfunction of ERA5 data extraction task

### ISSUE THREAD

**Issue by mmmmansour** [SARRA-cropmodels/SARRA-data-download#6]
When downloading and extracting ERA5 data, a problem occurred. It was a malfunction during the extraction task and was due to the length of the extraction path.

**Comment by codename5281** [comment]
Hello @mmmmansour ,
Thanks for your feedback, 
As discussed this could be a Windows-specific behavior related to bad management of filename length,
Could you try to force-activate management of long filenames ? There seems to be an option accessible from the registry editor, see [this tutorial](https://forums.cnetfrance.fr/tutoriels-windows-10/6639887-windows-10-comment-garder-un-nom-de-fichier-long). In the meantime, i will look for any workaround, but AgERA filenames are already naturally long.
Let us know if this works !

**Comment by codename5281** [comment]
As seen with @mmmmansour the proposed workaround for Windows (activation of an option through the registry editor, see [tutorial](https://forums.cnetfrance.fr/tutoriels-windows-10/6639887-windows-10-comment-garder-un-nom-de-fichier-long)  worked and allowed to manage long filenames. Closing issue.
